### ISSUE TITLE
Firefox UI issue (webcompat issue)

### ISSUE THREAD

**Issue by ajvb** [duo-labs/journal#1]
The nav bar is partially "hidden" on Firefox. Tested on Firefox Nightly 71 and Firefox Stable 69.

![journal-fx-compat-issue](https://user-images.githubusercontent.com/1144310/66674789-a7cb4e80-ec18-11e9-872e-d090b5adddd8.png)

**Comment by jordan-wright** [comment]
Hi @ajvb,

Thanks for the heads up! Things should be fixed now. You can find the updates at https://duo-labs.github.io/journal.

Let me know if you continue to run into issues. Thanks again for sending this over!

**Comment by ajvb** [comment]
Hey @jordan-wright - looks great now! Thanks for the quick response.
